config/routes.rb
Rails.application.routes.draw do
  resources :health_checks
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/health_check.rb
class HealthCheck < ApplicationRecord
  validates :note, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/health_checks_controller.rb
class HealthChecksController < ApplicationController
  before_action :set_health_check, only: [:show, :edit, :update, :destroy]

  # GET /health_checks
  # GET /health_checks.json
  def index
    @health_checks = HealthCheck.all
  end

  # GET /health_checks/1
  # GET /health_checks/1.json
  def show
  end

  # GET /health_checks/new
  def new
    @health_check = HealthCheck.new
  end

  # GET /health_checks/1/edit
  def edit
  end

  # POST /health_checks
  # POST /health_checks.json
  def create
    @health_check = HealthCheck.new(health_check_params)

    respond_to do |format|
      if @health_check.save
        format.html { redirect_to @health_check, notice: 'Health check was successfully created.' }
        format.json { render :show, status: :created, location: @health_check }
      else
        format.html { render :new }
        format.json { render json: @health_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /health_checks/1
  # PATCH/PUT /health_checks/1.json
  def update
    respond_to do |format|
      if @health_check.update(health_check_params)
        format.html { redirect_to @health_check, notice: 'Health check was successfully updated.' }
        format.json { render :show, status: :ok, location: @health_check }
      else
        format.html { render :edit }
        format.json { render json: @health_check.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /health_checks/1
  # DELETE /health_checks/1.json
  def destroy
    @health_check.destroy
    respond_to do |format|
      format.html { redirect_to health_checks_url, notice: 'Health check was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_health_check
      @health_check = HealthCheck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def health_check_params
      params.fetch(:health_check).permit(:note)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/health_checks_helper.rb
module HealthChecksHelper
end

app/views/health_checks/_form.html.erb
<%= form_with(model: health_check, local: true) do |form| %>
  <% if health_check.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(health_check.errors.count, "error") %> prohibited this health_check from being saved:</h2>

      <ul>
      <% health_check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div id="note-container">
    <%#= form.text_field :note %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<script>
  setTimeout(function (){
    document.getElementById('note-container').innerHTML = '<input type="text" name="health_check[note]" id="health_check_note">';
  }, 3000);
</script>

app/views/health_checks/edit.html.erb
<h1>Editing Health Check</h1>

<%= render 'form', health_check: @health_check %>

<%= link_to 'Show', @health_check %> |
<%= link_to 'Back', health_checks_path %>

app/views/health_checks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Health Checks</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Note</th>
      <th>Created At</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @health_checks.each do |health_check| %>
      <tr>
        <td><%= health_check.id %></td>
        <td><%= health_check.note %></td>
        <td><%= health_check.created_at %></td>
        <td><%= link_to 'Show', health_check %></td>
        <td><%= link_to 'Edit', edit_health_check_path(health_check) %></td>
        <td><%= link_to 'Destroy', health_check, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Health Check', new_health_check_path %>

app/views/health_checks/new.html.erb
<h1>New Health Check</h1>

<%= render 'form', health_check: @health_check %>

<%= link_to 'Back', health_checks_path %>

app/views/health_checks/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_health_check_path(@health_check) %> |
<%= link_to 'Back', health_checks_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DockerRailsExample</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>